<?php
declare(strict_types=1);

namespace vDesk\DataProvider\Expression;

use vDesk\DataProvider\IExpression;

/**
 * Interface that represents an INSERT SQL expression.
 *
 * @package vDesk\DataProvider\Expression
 * @author  Kerry Holz <DevelopmentHero@gmail.com>
 * @version 1.0.0
 */
interface IInsert extends IExpression {
    
    /**
     * Applies a specified target table to the IInsert.
     *
     * @param string $Table  The table to insert any values.
     * @param array  $Fields The fields of multiple values to insert.
     *
     * @return \vDesk\DataProvider\Expression\IInsert The current instance for further chaining.
     */
    public function Into(string $Table, array $Fields = []): IInsert;
    
    /**
     * Applies one or more fields and values to the IInsert.
     *
     * @param mixed[] $Values      The fields and values to insert.
     * @param array   ...$Multiple Additional values to insert.
     *
     * @return \vDesk\DataProvider\Expression\IInsert The current instance for further chaining.
     */
    public function Values(array $Values, array ...$Multiple): IInsert;

    /**
     * Executes the IInsert and retrieves the last insert ID.
     *
     * @return int Tha last insert ID generated by an auto incrementation column.
     */
    public function ID(): int;

}